<div class="container-fluid">
    <!--==================================
    =            Contact Form            =
    ===================================-->
    <section class="section contact mt50">
        <!-- container start -->

        <div class="seach-wrap">
            <div>
                <div class="seach-cont">
                    <i class="fa fa-search search-icon search-icon-wrap"></i>
                    <input type="text" class="search-input" placeholder="Search for Pathlab or Test" value="" autocomplete="off">
                    <span class="esc-wrap">
                        <i class="fa fa-close close-icon"></i>
                        <span class="esc-cont">ESC</span>
                    </span>
                </div>
            </div>




            <div class="mt50 clearfix"></div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs nav-justified indigo" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#panel5" role="tab"><i class="fa fa-building"></i> Pathlab</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#panel6" role="tab"><i class="fa fa-clipboard"></i> Test</a>
                </li>

            </ul>
            <!-- Tab panels -->
            <div class="tab-content">
                <!--Panel 1-->
                <div class="tab-pane fade in active" id="panel5" role="tabpanel">
                    <div class="lab-cont"> 
                        <div class="mt0">
                            <div class="lab-cont-inner">
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/hind-lab.jpg"></div>
                                                    <div class="exclusive">
                                                        <div class="exclusive-text">Exclusive</div>
                                                    </div>
                                                    <div class="mt14">
                                                        <div class="lab-title">Hind Path Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/dr-lal.jpg"></div>
                                                    <!--<div class="exclusive"><div class="exclusive-text">Exclusive</div></div>-->
                                                    <div class="mt14">
                                                        <div class="lab-title">Hind Path Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/idc-lab.jpg"></div>
                                                    <div class="exclusive">
                                                        <div class="exclusive-text">Exclusive</div>
                                                    </div>
                                                    <div class="mt14">
                                                        <div class="lab-title">Islamabad Path Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/morden-dignostic.jpg"></div>
                                                    <!--<div class="exclusive"><div class="exclusive-text">Exclusive</div></div>-->
                                                    <div class="mt14">
                                                        <div class="lab-title">Morden Dignostic Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/galaxy-lab.jpg"></div>
                                                    <div class="exclusive">
                                                        <div class="exclusive-text">Exclusive</div>
                                                    </div>
                                                    <div class="mt14">
                                                        <div class="lab-title">Galaxy Path Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/morden-dignostic2.jpg"></div>
                                                    <div class="exclusive">
                                                        <div class="exclusive-text">Exclusive</div>
                                                    </div>
                                                    <div class="mt14">
                                                        <div class="lab-title">Morden Dignostic  Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/morden-lab.jpg"></div>
                                                    <div class="exclusive">
                                                        <div class="exclusive-text">Exclusive</div>
                                                    </div>
                                                    <div class="mt14">
                                                        <div class="lab-title">Morden Path Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <div class="lab-cont-inner_A"> <a href="#" class="lab-cont-inner_A-cont">
                                            <div class="lab-cont-inner_A-padd">
                                                <div class="lab-cont-inner_A-img">
                                                    <div class="lab-cont-img_cont"> <img class="_2tuBw _12_oN" alt="Chai Point" width="254" height="160" src="images/labs/pov-digital.jpg"></div>
                                                    <div class="exclusive">
                                                        <div class="exclusive-text">Exclusive</div>
                                                    </div>
                                                    <div class="mt14">
                                                        <div class="lab-title">Pov Path Lab</div>
                                                        <div class="lab-sub-title" title="Fast Food, Beverages">Fully Computerise Laboratary</div>
                                                    </div>
                                                    <div class="detail-cont">
                                                        <div class="detail-cont_inner green-bg"><span class="fa fa-star icon-star_size"></span><span>4.4</span></div>
                                                        <div>•</div>
                                                        <div>56 MINS</div>
                                                        <div>•</div>
                                                        <div class="price"><i class="fa fa-rupee"></i> 300 FOR TWO Test</div>
                                                    </div>
                                                    <div class="offer-cont"><span class="fa fa-certificate certificate-size"><i class="fa-percent fa percentage"></i></span><span class="sNAfh">Free delivery on all orders</span></div>
                                                </div>
                                                <div class="view_btn"><span role="button" aria-label="Open" class="_2ECk4 _24tlh">Quick View</span></div>
                                            </div>
                                        </a> </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--/.Panel 1-->
                <!--Panel 2-->
                <div class="tab-pane fade" id="panel6" role="tabpanel">
                    <div class="lab-cont">
                        <div class="test-wrap">
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="test-img-cont"><img src="images/labs/hind-lab.jpg"/></div>				
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="row">
                                    <div class="col-md-8 col-sm-12 col-xs-12">
                                        <h3 class="test-title">Mini Aarogyama</h3>
                                        <p class="test-sub-title">Hind Pathlab </p>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12 test-price">
                                        <i class="fa fa-rupee"></i> 5600
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <a href="/" class="add-cart-btn">Add to Cart</a>
                            </div>
                        </div>
                        <div class="test-wrap">
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="test-img-cont"><img src="images/labs/dr-lal.jpg"/></div>				
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="row">
                                    <div class="col-md-8 col-sm-12 col-xs-12">
                                        <h3 class="test-title">Mini Aarogyama A</h3>
                                        <p class="test-sub-title">Dr. LaL Pathlab </p>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12 test-price">
                                        <i class="fa fa-rupee"></i> 3600
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <a href="/" class="add-cart-btn">Add to Cart</a>
                            </div>
                        </div>
                        <div class="test-wrap">
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="test-img-cont"><img src="images/labs/idc-lab.jpg"/></div>				
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="row">
                                    <div class="col-md-8 col-sm-12 col-xs-12">
                                        <h3 class="test-title">Diabetes Panel 1</h3>
                                        <p class="test-sub-title">IDC Pathlab </p>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12 test-price">
                                        <i class="fa fa-rupee"></i> 5600
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <a href="/" class="add-cart-btn">Add to Cart</a>
                            </div>
                        </div>
                        <div class="test-wrap">
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="test-img-cont"><img src="images/labs/hind-lab.jpg"/></div>				
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="row">
                                    <div class="col-md-8 col-sm-12 col-xs-12">
                                        <h3 class="test-title">Mini Aarogyama</h3>
                                        <p class="test-sub-title">Hind Pathlab </p>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12 test-price">
                                        <i class="fa fa-rupee"></i> 5600
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <a href="/" class="add-cart-btn">Add to Cart</a>
                            </div>
                        </div>
                        <div class="test-wrap">
                            <div class="col-md-2 col-sm-6 col-xs-12">
                                <div class="test-img-cont"><img src="images/labs/hind-lab.jpg"/></div>				
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div class="row">
                                    <div class="col-md-8 col-sm-12 col-xs-12">
                                        <h3 class="test-title">Mini Aarogyama</h3>
                                        <p class="test-sub-title">Hind Pathlab </p>
                                    </div>
                                    <div class="col-md-4 col-sm-6 col-xs-12 test-price">
                                        <i class="fa fa-rupee"></i> 5600
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <a href="/" class="add-cart-btn">Add to Cart</a>
                            </div>
                        </div>

                        <div class="clearfix">&nbsp;</div>
                    </div>

                </div>
                <!--/.Panel 2--> 
            </div>
        </div>

        <!-- container end -->
    </section> 
    <div class="clearfix">&nbsp;</div>
</div>
<div class="clearfix">&nbsp;</div>

<!-- Modal -->
<div class="modal fade" id="cityModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close font16" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="exampleModalLabel">Serch Location</h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12  col-xs-12"><input type="text" class="form-control" value="" name="" placeholder="Search for area, street name.."></div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="js/bootstrap.min.js"></script>

<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"></script>
<script src="google-map/gmap.js"></script>


<script type="text/javascript">
    $(document).ready(function () {
        $window = $(window);
        $(window).scroll(function () {
            if ($window.scrollTop() > 10)
                $("body").addClass("sticky");
            else
                $("body").removeClass("sticky");
            if ($window.scrollTop() > 300)
                $("body").addClass("sticky_more");
            else
                $("body").removeClass("sticky_more");
        });
    });
</script>
