<head>
    <title>Best Hompiq Pathology Labs in Delhi NCR, Best Clinical Path Labs, Blood Test Lab Near me, Best diagnostic Lab Centre in South Delhi, Nabl certified labs</title>
    <meta name="description" content="Blood test lab near me - Hompiq Laboratory is a well established Pathology Testing Laboratories in New Delhi / NCR India Diagnostic Centres in Delhi, Pathology Lab Delhi India, Pathology Testing Lab, Diagnostic Lab in Delhi, Path Lab. Online blood test at home near me, home collection blood test, sample collection from home diagnostic centre in Delhi NCR">
    <meta name="keywords" content="diagnostic centre in delhi, best diagnostic centre in delhi, blood test in delhi, nabl lab in delhi, blood test lab, blood test lab near me, Pathology lab in delhi, Diagnostic Centre, Hompiq Laboratory Pathology Services,  pathology india, Pathology Lab">

    <link href="<?php echo $this->basePath() ?>/public/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />

    <link href="<?php echo $this->basePath() ?>/public/css/style.css" rel="stylesheet" type="text/css" media="all" /> 
    <link href="<?php echo $this->basePath() ?>/public/css/responsive-1.css" rel="stylesheet">
    <link href="<?php echo $this->basePath() ?>/public/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<div ng-app="app">

    <script>
        var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
        var city = 0;
    </script>

    <header>
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                    <a href="<?php echo $this->basePath() ?>" class="logo"><img src="<?php echo $this->basePath() ?>/public/images/logo-small.png" alt=""></a>
                    <div class="search-cont"> <span class="cityname"><span class="cityname-bold">Gurugram</span></span> <span class="state"> Haryana, India</span> <span class="icon-downArrow arrow-cont"></span> </div>
                </div>
                <!-- top-nav -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->basePath() ?>/application/index/search" class="active"><i class="fa fa-search"></i> Search</a></li>
                        <li><a href="help.html"><i class="fa-tags fa"></i> Help</a></li>
                        <li><a href="sign.html"><i class="fa-user-o fa"></i> Sign in</a></li>
                        <li><a href="cart.html"><i class="fa-shopping-bag fa"></i> Cart</a></li>
                    </ul>
                    <div class="clearfix"> </div>
                </div>
            </nav>
        </div>
    </header>
    <body>